"""update candidate profile experience type

Revision ID: 03c9b1a1f7a2
Revises: fd9bd9786dc4
Create Date: 2026-09-05 09:53:00.075710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '03c9b1a1f7a2'
down_revision: Union[str, Sequence[str], None] = 'fd9bd9786dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_ats_resume_job'), table_name='ats_analyses')
    op.create_unique_constraint('uq_ats_analysis_resume_job', 'ats_analyses', ['resume_id', 'job_id'])
    op.alter_column('candidate_profiles', 'experience_years',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=3, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_profiles', 'experience_years',
               existing_type=sa.Numeric(precision=3, scale=1),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_constraint('uq_ats_analysis_resume_job', 'ats_analyses', type_='unique')
    op.create_index(op.f('uq_ats_resume_job'), 'ats_analyses', ['resume_id', 'job_id'], unique=True)
    # ### end Alembic commands ###
