"""add ats analyses

Revision ID: fd9bd9786dc4
Revises: b933ccb4d611
Create Date: 2026-08-25 20:10:21.027690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9bd9786dc4'
down_revision: Union[str, Sequence[str], None] = 'b933ccb4d611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ats_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skill_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('education_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('keyword_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('matched_keywords', sa.JSON(), nullable=True),
    sa.Column('missing_keywords', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'job_id', name='uq_ats_resume_job')
    )
    op.create_index(op.f('ix_ats_analyses_id'), 'ats_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_ats_analyses_job_id'), 'ats_analyses', ['job_id'], unique=False)
    op.create_index(op.f('ix_ats_analyses_resume_id'), 'ats_analyses', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ats_analyses_resume_id'), table_name='ats_analyses')
    op.drop_index(op.f('ix_ats_analyses_job_id'), table_name='ats_analyses')
    op.drop_index(op.f('ix_ats_analyses_id'), table_name='ats_analyses')
    op.drop_table('ats_analyses')
    # ### end Alembic commands ###
